name: Deployment

on:
  push:
    branches:
      - main
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci --no-audit --no-optional --fund=false
      - name: Build JavaScript files
        run: npm run build
      - name: Configure AWS credentials
        run: |
          aws configure set region us-east-2
          aws configure set aws_access_key_id "${{ secrets.AWS_KEY }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET }}"
      - name: Install Serverless CLI
        run: npm install -g serverless
      - name: Deploy to proper stage
        run: serverless deploy --stage "${GITHUB_REF_NAME}"
